latexdiff
SQRT and SQRTNB command was added so it could handle a space after the sqrt.
for example: \sqrt n
SUPERSCRIPT and SUBSCRIPT handle spaces and not having {}
for example: 2^  n or 2^   {n} or k_   i or k_   {i}
=> sqrt command was added to pre/postprocessing

latexdiff
This fixes a bug where an included file could not have dots on it when
being flattened.
=> Make sure the extension is at the end of the file.

latexdiff-vc
$options was set to '' when @ldoptions was empty, which was messing up
the latexdiff command. Add conditional to avoid this problem.
=> Add conditional for empty ldoptions (fixes issue #58)

latexdiff
Handling items breaks if the \item is followed by a command. For removing this code:
```
\begin{itemize}
\item \verb{my_id_t} for reference see \myref{sec:my_id_t}.
\end{itemize}
```
The result was:
```
%DIFDELCMD < \begin{itemize}
\begin{itemize}%DIFAUXCMD
%DIFDELCMD < \item \verb{my_id_t} %%%
\DIFdel{type, see
}%DIFDELCMD < \myref{sec:my_id_t}%%%
\DIFdel{.
}
\end{itemize}%DIFAUXCMD
%DIFDELCMD < \end{itemize}
```
Probably, this is not only a problem for commands? Should we check for more than just `$cmdoptseq`?
=> restore \item, even if there is an unsafe command after the item

latexdiff-vc
Since pdftk has been deprecated by some distributions, and can be difficult to install for some users, this PR adds support for qpdf, falling back on pdftk if qpdf is unavailable.  None of the logic or output changes, just the command used to create the stripped pdf.
=> add qpdf support in addition to pdftk for --only-changes

latexdiff
Hi ftilmann. I had a problem with latexdiff when updating my arch system. I found a post on the arch forum (https://bbs.archlinux.org/post.php?tid=226993), but the solution did not work for me. So I tried to fix it on my own. Luckily, it was a trivial problem (I have exactly 0 experience with perl).
A negative number is given to the repeat operator "x" when adding spaces for proper alignment of the labels (file names). I guess with an older perl version a negative number was just not evaluated? 
I did not really check for any style guides and I guess you might have chosen other variable names (I can change this, if you request it). Anyway, I just needed a working latexdiff quickly and wanted to share my solution (if this deserves the name).
=> fix error "Negative repeat count does nothing at..."

latexdiff
Consider extensions with 4 letters as also valid when expanding input, include and subfile commands
=> Solving issue #108 opened on Jul 2

latexdiff
Hi, 
this fixes a small issue with the "gathered" sub-environment 
of the "equation" environment. The fix is similar to the patch
that was fixing an analogues problem with the "aligned" sub-environment and that was introduced in the commit 
5fb12c5. 
Yours, 
Ivan
=> Support \begin{gathered}...\end{gathered}.

latexdiff-vc
config is not propagated properly from latexdiff-vc to the invoked latexdiff command
With this fix, also the final latexdiff has the config
=> Invoked latexdiff ignores the config argument without the equal sign

latexdiff
An alternative expression might be (but would actually capture the nested brackets, so ?1 would need to be adopted on use):
(\{(?:(?1)|[^{}]*+)++\})
I'm using perl 5.24.1 and get multiple of warnings on execution.
=> Perl is complaining about an unescaped left bracket

latexdiff
Add support for Tex \def macro to the Latex spliting pattern.
Let comment pattern match the first % in the line
=> Proposed solution for issue #122

latexdiff
Verbatim blocks are patched to comment-lines, this adds % in front.
Then `$` characters in comments are patched to DOLLARDIF.
If there was no change in the verbatim block, the % is removed.
Finally, the DOLLARDIF was not patched back. 
I think it should be quite safe, to patch all DOLLARDIF.
=> Fix issue with remaining DOLLARDIF in unchanged verbatim blocks

Makefile.dist
`make install` currently assumes that the target directories
`INSTALLPATH/{bin,man/man1}` already exist. This can lead to installation
errors when `INSTALLPATH` is overriden to install into arbitrary location.
This change causes `install` program to create target directories if
they don't exist.
Additionally the permissions of installed man pages are corrected to
644 instead of the default 755 - they don't need the exec bit.
=> Improve installation procedure

latexdiff
Commands listed in CUSTOMDIFCMD assume to have a ADD and DEL prefixed
version of the command defined by the document:
CUSTOMDIFCMD=blindtext
\newcommand{\DELblindtext}{\DIFdel{\blindtext}}
\newcommand{\ADDblindtext}{\DIFadd{\blindtext}}
This patch allows to show changes for commands that need special care. 
(We have commands for re-occuring paragraph headings. This allows to display the deleted/added paragraph name)
=> Add support for custom diff commands

latexdiff, latexdiff-vc
This flag avoids to have crosslinks in the document that would lead to
invalid pages in stripped pdf diff files.
Some tools and pdf viewers (e.g. preview in macos) have issues with 
links ranging to invalid pages in the document.
=> Add flag --no-links

latexdiff-vc
For a larger Resulting PDF size is smallest with gs, then pdftk and largest with qpdf.
This adds ghostscript and reorders priority from (qpdf, pdftk) to (gs, pdftk, qpdf)
Form a 1750700 byte PDF, an example diff with 2 changed pages results in these sizes for me:
84026  only-changedpage-gs.pdf
169703  only-changedpage-pdftk.pdf
426694  only-changedpage-qpdf.pdf
=> Add ghostscript (gs) support for creating more compact minimal diffs.

latexdiff
running pod2man -center=" " latexdiff > dist/latexdiff.1
(as done during 'make distribution')
found a syntax error:
latexdiff around line 4272: You can't have =items (as at line 4276) unless the first thing after the =over is an =item
POD document had syntax errors at /usr/bin/pod2man line 71.
=> fix POD syntax error

latexdiff
caption is already there, so subcaption should be treated the same
=> include 'subcaption' in CONTEXT1 COMMANDS

latexdiff
If there are more changes after the deleted verbatim block, this pattern
did not match and the removed verbatim did not show up in the diff.
Finding the `\end{verbatim}` should be sufficient. 
Removing the figure from this MWE would result in an empty section. With this patch, the removed code is shown:
```
\documentclass{book}
\begin{document}
\chapter{chapter1}
\begin{figure}
\begin{verbatim}
int main(int argc, char** argv){return 0;}
\end{verbatim}
\end{figure}
\end{document}
```
=> Fix issue for removing larger parts of a document

latexdiff
This commit adds a new command to mark beginning and end of a segment
that changed. This allows to mark changes in verbatim environments. The
difference from \DIFaddbegin &Co is that there is no further semantics
about changes given by this tag. For undo the diff, this command is simply
to be ignored.
=> Generate zlabels for changes in verbatim environments

latexdiff
As per Issue 165, --filter-script option added that is applied to both old and new files before diffing.
=> --filter-script option added

latexdiff
Fix for issue #172.
Extends _flatten_ to take directory argument, allowing \subimport to incrementally add to the search path, or \import to replace it.
Updated doc strings to reflect additional capability.
=> import package support (\import and \subimport commands)

latexdiff-vc
Fixed "requires the a version control system" to "requires a version control system"
=> Typo in manual

latexdiff-man.tex
This is simply the result of running the [aspell](http://aspell.net/) spellchecker:
```
aspell --lang=en --mode=tex check latexdiff-man.tex
```
Also noticed the "unstyled" LaTeX.
=> Fix the typos in the manual

Makefile.dist
Resolve #98 
Also, `make install fast` isn't a valid target, but `install-fast` is :-)
=> Provide uninstall command

latexdiff-vc
When dealing with big documents, at some point the excessive list of pages can exceed the limit supported by gs. All of the tools accept page ranges, so this patch merges 3 or more consecutive pages into a page range.
=> Merge page ranges for minimal diffs

latexdiff
When generating changebars, or other markup not using color for showing
added/removed sections, the preamble for the listings package shall not
pull in the color package as that will lead to added listings to be
blue even though no color is expected in this mode.
=> Add separate preamble for listings without the color package

latexdiff
Fix issue #218 by replacing the `\hspace{0pt}` statement with its TeX equivalent `\hskip0pt`, while still allowing line breaks between added and deleted citations.
=> Fix issue #218 (\hspace{0pt} after \mbox{..} causes error with newer versions of LaTeX)

latexdiff
This simply adds `multlined` (from the `amsmath` package) to the list of math array environments.
Note that I don't actually know Perl, I just copied #116 and it seems to work.
=> Support multlined array environment

latexdiff
This is not polished yet.
It sanitizes the cases in https://github.com/ftilmann/latexdiff/issues/50 and more, such as
```
\documentclass{article}
\begin{document}
\begin{equation}
x = \frac \lambda b
\end{equation}
\begin{equation}
x = \frac12
\end{equation}
\end{document}
```
with spaces added and removed at will.
It still gives warnings because it tries to print capture group variables which haven't captured anything. It also does not deal with newlines or comment symbols yet. I am not sure what is the best way to fix either of these issues.
=> sanitize more possible input schemata of frac

latexdiff, testsuite/no-del-new.tex, testsuite/no-del-old.tex, testsuite/verify
Fixes https://github.com/ftilmann/latexdiff/issues/66
* The name of the option can potentially be improved.
* Seems to work well in the body.
* Does not yet work well in title (and potentially other parts of the preamble).
* I could not find how to really **test**. It seems that `verify` just checks that things compile.
=> Adding option "--no-del" to include only additions

latexdiff
When we use the package `\subfiles` and if we load nested files with relative paths, e.g., if we have more `\subfiles` in a file read by `\subfile`, which is in some different directory, `latexdiff` cannot deal with the inner `\subfile`.
This is due to the fact that when expanding the `\subfile`, the argument to flatten is `$filename`, i.e. the current path.
https://github.com/ftilmann/latexdiff/blob/9d3a00aec26984018fdca1086ddff97af9678541/latexdiff#L1795
By changing `$filename` to `$fullfile`, i.e., the path of the file to read, the program can find the file even when there is nesting.
=> Fixed a bug that prevented finding nested subfiles

latexdiff
adding new macros of siunitx to mboxcmds or safecmdlist
Proposed solution to #282 
Macros of siunitx v.3 are added in
- add to mboxcmds: qty,qtylist,qtyproduct,qtyrange,complexqty
- add to safecmdlist: numproduct,unit,complexnum
=> adding new macros of siunitx

latexdiff-vc
Depending on the packages used, latexdiff-vc with option --only-changed is unable to parse changed pages, the reason being that \abspage{} might not be in last position.
=> Generalize regex in latexdiff-vc > findchangedpages
